-- Generated by pnpm db:sql from the lesson frontmatter. Safe to rerun.
BEGIN;
CREATE TABLE IF NOT EXISTS app_users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  google_sub text NOT NULL UNIQUE,
  email text NOT NULL UNIQUE CHECK (email ~ '^[^@[:space:]]+@snu[.]ac[.]kr$'),
  name text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  last_login_at timestamptz NOT NULL DEFAULT now(),
  disabled_at timestamptz
);
CREATE TABLE IF NOT EXISTS learning_items (
  id text PRIMARY KEY,
  week smallint NOT NULL CHECK (week BETWEEN 0 AND 8),
  kind text NOT NULL CHECK (kind IN ('concept','assignment')),
  label text NOT NULL
);
CREATE TABLE IF NOT EXISTS learning_progress (
  user_id uuid NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
  item_id text NOT NULL REFERENCES learning_items(id),
  completed boolean NOT NULL DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id,item_id)
);
CREATE INDEX IF NOT EXISTS learning_progress_item_completed ON learning_progress(item_id) WHERE completed;
CREATE INDEX IF NOT EXISTS learning_progress_updated ON learning_progress(updated_at DESC);
-- No public/anonymous database role: every app query is made on the server after session authorization.

CREATE TABLE IF NOT EXISTS week_quizzes (
 week smallint PRIMARY KEY CHECK (week BETWEEN 2 AND 8),
 questions jsonb NOT NULL DEFAULT '[]',
 instructions text NOT NULL DEFAULT '',
 password_hash text NOT NULL DEFAULT '',
 published boolean NOT NULL DEFAULT false,
 revision integer NOT NULL DEFAULT 1,
 updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS week_unlocks (
 user_id uuid NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
 week smallint NOT NULL CHECK (week BETWEEN 2 AND 8),
 unlocked_at timestamptz NOT NULL DEFAULT now(),
 PRIMARY KEY(user_id,week)
);
CREATE TABLE IF NOT EXISTS quiz_attempts (
 user_id uuid NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
 week smallint NOT NULL CHECK (week BETWEEN 2 AND 8),
 window_start timestamptz NOT NULL DEFAULT now(),
 attempts integer NOT NULL DEFAULT 1,
 PRIMARY KEY(user_id,week)
);
CREATE TABLE IF NOT EXISTS lesson_edits (
 week smallint PRIMARY KEY CHECK (week BETWEEN 0 AND 8),
 body text NOT NULL,
 revision integer NOT NULL DEFAULT 1,
 updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE lesson_edits ADD COLUMN IF NOT EXISTS colab_url text;
-- NULL uses the course notebook. Empty string hides the practice button.

INSERT INTO learning_items(id,week,kind,label) VALUES
('w0:Python',0,'concept','Python'),
('w0:NumPy',0,'concept','NumPy'),
('w0:Shape',0,'concept','Shape'),
('w0:assignment:Check',0,'assignment','Check'),
('w0:assignment:Apply',0,'assignment','Apply'),
('w0:assignment:Explore',0,'assignment','Explore'),
('w1:Model',1,'concept','Model'),
('w1:Parameter',1,'concept','Parameter'),
('w1:Prediction',1,'concept','Prediction'),
('w1:Target',1,'concept','Target'),
('w1:Loss',1,'concept','Loss'),
('w1:Feature',1,'concept','Feature'),
('w1:assignment:Check',1,'assignment','Check'),
('w1:assignment:Apply',1,'assignment','Apply'),
('w1:assignment:Explore',1,'assignment','Explore'),
('w2:Derivative',2,'concept','Derivative'),
('w2:Gradient',2,'concept','Gradient'),
('w2:Learning Rate',2,'concept','Learning Rate'),
('w2:Chain Rule',2,'concept','Chain Rule'),
('w2:assignment:Check',2,'assignment','Check'),
('w2:assignment:Apply',2,'assignment','Apply'),
('w2:assignment:Explore',2,'assignment','Explore'),
('w3:Vector',3,'concept','Vector'),
('w3:Dot Product',3,'concept','Dot Product'),
('w3:Hyperplane',3,'concept','Hyperplane'),
('w3:Perceptron',3,'concept','Perceptron'),
('w3:assignment:Check',3,'assignment','Check'),
('w3:assignment:Apply',3,'assignment','Apply'),
('w3:assignment:Explore',3,'assignment','Explore'),
('w4:Feature Space',4,'concept','Feature Space'),
('w4:Polynomial Features',4,'concept','Polynomial Features'),
('w4:Linear Separability',4,'concept','Linear Separability'),
('w4:assignment:Check',4,'assignment','Check'),
('w4:assignment:Apply',4,'assignment','Apply'),
('w4:assignment:Explore',4,'assignment','Explore'),
('w5:MLP',5,'concept','MLP'),
('w5:Activation',5,'concept','Activation'),
('w5:ReLU',5,'concept','ReLU'),
('w5:Backpropagation',5,'concept','Backpropagation'),
('w5:assignment:Check',5,'assignment','Check'),
('w5:assignment:Apply',5,'assignment','Apply'),
('w5:assignment:Explore',5,'assignment','Explore'),
('w6:Logit',6,'concept','Logit'),
('w6:Softmax',6,'concept','Softmax'),
('w6:Cross-Entropy',6,'concept','Cross-Entropy'),
('w6:Batch',6,'concept','Batch'),
('w6:Epoch',6,'concept','Epoch'),
('w6:Generalization',6,'concept','Generalization'),
('w6:Overfitting',6,'concept','Overfitting'),
('w6:assignment:Check',6,'assignment','Check'),
('w6:assignment:Apply',6,'assignment','Apply'),
('w6:assignment:Explore',6,'assignment','Explore'),
('w7:Convolution',7,'concept','Convolution'),
('w7:Filter',7,'concept','Filter'),
('w7:Feature Map',7,'concept','Feature Map'),
('w7:Pooling',7,'concept','Pooling'),
('w7:Inductive Bias',7,'concept','Inductive Bias'),
('w7:assignment:Check',7,'assignment','Check'),
('w7:assignment:Apply',7,'assignment','Apply'),
('w7:assignment:Explore',7,'assignment','Explore'),
('w8:Residual',8,'concept','Residual'),
('w8:Skip Connection',8,'concept','Skip Connection'),
('w8:Batch Normalization',8,'concept','Batch Normalization'),
('w8:ResNet',8,'concept','ResNet'),
('w8:assignment:Check',8,'assignment','Check'),
('w8:assignment:Apply',8,'assignment','Apply'),
('w8:assignment:Explore',8,'assignment','Explore')
ON CONFLICT(id) DO UPDATE SET week=EXCLUDED.week,kind=EXCLUDED.kind,label=EXCLUDED.label;
COMMIT;
