import fs from "node:fs";
import { catalog, schema } from "./db-catalog.mjs";
const quote = (s) => "'" + String(s).replaceAll("'", "''") + "'";
const rows = catalog()
  .map((i) => `(${quote(i.id)},${i.week},${quote(i.kind)},${quote(i.label)})`)
  .join(",\n");
fs.writeFileSync(
  "db/setup.sql",
  "-- Generated by pnpm db:sql from the lesson frontmatter. Safe to rerun.\nBEGIN;\n" +
    schema() +
    `\nINSERT INTO learning_items(id,week,kind,label) VALUES\n${rows}\nON CONFLICT(id) DO UPDATE SET week=EXCLUDED.week,kind=EXCLUDED.kind,label=EXCLUDED.label;\nCOMMIT;\n`,
);
console.log("db/setup.sql 생성 완료 (Neon SQL Editor에서 실행할 수 있습니다).");
